In [ ]:
'''
【课程1.2】  Numpy基础数据结构

NumPy数组是一个多维数组对象，称为ndarray。其由两部分组成：
① 实际的数据
② 描述这些数据的元数据

'''

In [19]:
# 多维数组ndarray
import numpy as np

ar = np.array([1,2,3,4,5,6,7])
print(ar)          # 输出数组，注意数组的格式：中括号，元素之间没有逗号（和列表区分）
print(ar.ndim)     # 输出数组维度的个数（轴数），或者说“秩”，维度的数量也称rank
print(ar.shape)    # 数组的维度，对于n行m列的数组，shape为（n，m）
print(ar.size)     # 数组的元素总数，对于n行m列的数组，元素总数为n*m
print(ar.dtype)    # 数组中元素的类型，类似type()（注意了，type()是函数，.dtype是方法）
print(ar.itemsize) # 数组中每个元素的字节大小，int32l类型字节为4，float64的字节为8
print(ar.data)     # 包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性。
ar   # 交互方式下输出，会有array(数组)

# 数组的基本属性
# ① 数组的维数称为秩（rank），一维数组的秩为1，二维数组的秩为2，以此类推
# ② 在NumPy中，每一个线性的数组称为是一个轴（axes），秩其实是描述轴的数量：
# 比如说，二维数组相当于是两个一维数组，其中第一个一维数组中每个元素又是一个一维数组
# 所以一维数组就是NumPy中的轴（axes），第一个轴相当于是底层数组，第二个轴是底层数组里的数组。
# 而轴的数量——秩，就是数组的维数。

[1 2 3 4 5 6 7]
1
(7,)
7
int32
4


array([1, 2, 3, 4, 5, 6, 7])

In [27]:
# 创建数组：array()函数，括号内可以是列表、元祖、数组、生成器等


ar1 =np.array(range(10))
ar2 = np.arange(10)
ar3 = np.array([1,2,3,4,5])
ar4 = np.array([[1,2,3,4,5],['a','b','c','d','e']])
print(ar1)
print(ar2)
print(ar3)
print(ar4)
print(np.random.rand(10).reshape(2,5))




[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]
[['1' '2' '3' '4' '5']
 ['a' 'b' 'c' 'd' 'e']]
[[0.12469962 0.4337781  0.09666806 0.4879381  0.29977933]
 [0.12696355 0.91392259 0.60784128 0.73455587 0.81691907]]


In [ ]:
# 创建数组：arange()，类似range()，在给定间隔内返回均匀间隔的值。

print(np.arange(10))    # 返回0-9，整型
print(np.arange(10.0))  # 返回0.0-9.0，浮点型
print(np.arange(5,12))  # 返回5-11
print(np.arange(5.0,12,2))  # 返回5.0-12.0，步长为2
print(np.arange(10000))  # 如果数组太大而无法打印，NumPy会自动跳过数组的中心部分，并只打印边角：


